apiVersion: v1
kind: Service
metadata:
  name: {{ include "lttl.fullname" . }}-kong
  labels:
    {{- include "lttl.labels" . | nindent 4 }}
    app.kubernetes.io/component: kong
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 8000
      targetPort: proxy
    - name: admin
      port: 8001
      targetPort: admin
  selector:
    {{- include "lttl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kong

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lttl.fullname" . }}-kong
  labels:
    {{- include "lttl.labels" . | nindent 4 }}
    app.kubernetes.io/component: kong
spec:
  replicas: {{ .Values.kong.replicas }}
  selector:
    matchLabels:
      {{- include "lttl.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kong
  template:
    metadata:
      labels:
        {{- include "lttl.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kong
    spec:
      containers:
        - name: kong
          image: {{ .Values.kong.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: proxy
              containerPort: 8000
            - name: admin
              containerPort: 8001
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /usr/local/kong/declarative/kong.yaml
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_PROXY_LISTEN
              value: 0.0.0.0:8000
          readinessProbe:
            httpGet:
              path: /status
              port: admin
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.kong.resources | nindent 12 }}
          volumeMounts:
            - name: kong-config
              mountPath: /usr/local/kong/declarative/kong.yaml
              subPath: kong.yaml
              readOnly: true
      volumes:
        - name: kong-config
          configMap:
            name: {{ include "lttl.fullname" . }}-kong
