{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "lttl.fullname" . }}-keyvault
  labels:
    {{- include "lttl.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: rabbitmq-password
          objectType: secret
        - |
          objectName: rabbitmq-erlang-cookie
          objectType: secret
        - |
          objectName: keycloak-admin-password
          objectType: secret
        - |
          objectName: keycloak-client-secret
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
        - |
          objectName: storage-account-name
          objectType: secret
        - |
          objectName: storage-account-key
          objectType: secret
  secretObjects:
    - secretName: {{ include "lttl.secretName" . }}
      type: Opaque
      data:
        - objectName: postgres-password
          key: POSTGRES_PASSWORD
        - objectName: rabbitmq-password
          key: RABBITMQ_DEFAULT_PASS
        - objectName: rabbitmq-erlang-cookie
          key: RABBITMQ_ERLANG_COOKIE
        - objectName: keycloak-admin-password
          key: KEYCLOAK_ADMIN_PASSWORD
        - objectName: keycloak-client-secret
          key: KEYCLOAK_CLIENT_SECRET
        - objectName: redis-password
          key: REDIS_PASSWORD
        - objectName: storage-account-name
          key: STORAGE_ACCOUNT_NAME
        - objectName: storage-account-key
          key: STORAGE_ACCOUNT_KEY
{{- end }}
