apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lttl.secretName" . }}
  labels:
    {{- include "lttl.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.rabbitmqUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmqPassword | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.secrets.rabbitmqErlangCookie | quote }}
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloakAdmin | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloakClientSecret | quote }}
  STORAGE_ACCOUNT_NAME: {{ .Values.secrets.storageAccountName | quote }}
  STORAGE_ACCOUNT_KEY: {{ .Values.secrets.storageAccountKey | quote }}
  STORAGE_CONTAINER_NAME: {{ .Values.secrets.storageContainerName | quote }}
  STORAGE_PRESIGNED_URL_EXPIRY: {{ .Values.secrets.storagePresignedUrlExpiry | quote }}
  realm-export.json: |
    {
      "realm": {{ .Values.secrets.keycloakRealm | quote }},
      "enabled": true,
      "registrationAllowed": false,
      "resetPasswordAllowed": true,
      "loginWithEmailAllowed": true,
      "roles": {
        "realm": [
          { "name": "ADMIN" },
          { "name": "CENTER_MANAGER" },
          { "name": "INSTRUCTOR" },
          { "name": "STUDENT" }
        ]
      },
      "clients": [
        {
          "clientId": {{ .Values.secrets.keycloakClientId | quote }},
          "name": "NestJS Backend",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": {{ .Values.secrets.keycloakClientSecret | quote }},
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "redirectUris": ["*"],
          "webOrigins": ["*"]
        }
      ]
    }
{{- if .Values.imagePullSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lttl.imagePullSecretName" . }}
  labels:
    {{- include "lttl.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" (dict .Values.imagePullSecret.registry (dict "username" .Values.imagePullSecret.username "password" .Values.imagePullSecret.token "auth" (printf "%s:%s" .Values.imagePullSecret.username .Values.imagePullSecret.token | b64enc))) | toJson | b64enc | quote }}
{{- end }}
