#!/bin/sh
# Consul bootstrap script

set -e

CONSUL_URL="${CONSUL_URL:-http://consul:8500}"
POSTGRES_USER="${POSTGRES_USER:-user}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-password}"
RABBITMQ_DEFAULT_USER="${RABBITMQ_DEFAULT_USER:-guest}"
RABBITMQ_DEFAULT_PASS="${RABBITMQ_DEFAULT_PASS:-guest}"
KEYCLOAK_CLIENT_SECRET="${KEYCLOAK_CLIENT_SECRET:-change-me}"
KEYCLOAK_TIMEOUT_MS="${KEYCLOAK_TIMEOUT_MS:-10000}"
STORAGE_ACCOUNT_NAME="${STORAGE_ACCOUNT_NAME:-}"
STORAGE_ACCOUNT_KEY="${STORAGE_ACCOUNT_KEY:-}"
STORAGE_CONTAINER_NAME="${STORAGE_CONTAINER_NAME:-media}"
STORAGE_PRESIGNED_URL_EXPIRY="${STORAGE_PRESIGNED_URL_EXPIRY:-3600}"
GATEWAY_PUBLIC_URL="${GATEWAY_PUBLIC_URL:-http://localhost:8000}"
KEYCLOAK_PUBLIC_URL="${KEYCLOAK_PUBLIC_URL:-http://localhost:8080}"
FRONTEND_ORIGIN="${FRONTEND_ORIGIN:-http://localhost:3000}"
KONG_CORS_ORIGINS="${KONG_CORS_ORIGINS:-http://localhost:3000,http://localhost:3001,http://localhost:3009,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:3001,http://127.0.0.1:3009,http://127.0.0.1:5173}"
MAX_RETRIES=30
RETRY_COUNT=0

MEDIA_STORAGE_CONFIGURED="false"
if [ -n "$STORAGE_ACCOUNT_NAME" ] && [ -n "$STORAGE_ACCOUNT_KEY" ]; then
  MEDIA_STORAGE_CONFIGURED="true"
else
  echo "[Consul] Media storage credentials are not configured; media upload endpoints will stay disabled"
fi

echo "[Consul] Waiting for Consul to be ready..."

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
  if curl -s "$CONSUL_URL/v1/status/leader" > /dev/null 2>&1; then
    echo "[Consul] Consul is ready"
    break
  fi

  RETRY_COUNT=$((RETRY_COUNT + 1))
  echo "[Consul] Waiting... ($RETRY_COUNT/$MAX_RETRIES)"
  sleep 1
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
  echo "[Consul] Consul failed to become ready"
  exit 1
fi

set_kv() {
  key="$1"
  value="$2"
  display_value="$value"
  case "$key" in
    *password*|*Password*|*secret*|*Secret*|*accountKey*|*AccountKey*)
      display_value="***"
      ;;
  esac
  echo "[Consul] Setting: $key = $display_value"
  # Store as JSON-encoded string so Consul UI JSON mode works correctly
  json_value=$(printf '"%s"' "$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')")
  curl -s -X PUT -d "$json_value" "$CONSUL_URL/v1/kv/$key" > /dev/null
}

delete_kv() {
  key="$1"
  echo "[Consul] Deleting optional key: $key"
  curl -s -X DELETE "$CONSUL_URL/v1/kv/$key" > /dev/null
}

seed_media_storage() {
  env_name="$1"
  if [ "$MEDIA_STORAGE_CONFIGURED" = "true" ]; then
    set_kv "config/$env_name/media-service/storage.accountName" "${STORAGE_ACCOUNT_NAME}"
    set_kv "config/$env_name/media-service/storage.accountKey" "${STORAGE_ACCOUNT_KEY}"
    set_kv "config/$env_name/media-service/storage.containerName" "${STORAGE_CONTAINER_NAME}"
    set_kv "config/$env_name/media-service/storage.presignedUrlExpiry" "${STORAGE_PRESIGNED_URL_EXPIRY}"
  else
    delete_kv "config/$env_name/media-service/storage.accountName"
    delete_kv "config/$env_name/media-service/storage.accountKey"
    delete_kv "config/$env_name/media-service/storage.containerName"
    delete_kv "config/$env_name/media-service/storage.presignedUrlExpiry"
  fi
}

echo "[Consul] Loading development configuration..."
set_kv "config/development/shared/log.level" "debug"
set_kv "config/development/shared/log.format" "text"
set_kv "config/development/shared/node_env" "development"
set_kv "config/development/shared/public.gateway.url" "${GATEWAY_PUBLIC_URL}"
set_kv "config/development/shared/public.keycloak.url" "${KEYCLOAK_PUBLIC_URL}"
set_kv "config/development/shared/public.frontend.origin" "${FRONTEND_ORIGIN}"
set_kv "config/development/shared/cors.origins" "${KONG_CORS_ORIGINS}"
set_kv "config/development/identity-service/port" "3000"
set_kv "config/development/identity-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-identity:5432/identity_db"
set_kv "config/development/identity-service/database.pool_size" "10"
set_kv "config/development/identity-service/database.connection_timeout" "5000"
set_kv "config/development/identity-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/identity-service/rabbitmq.username" "${RABBITMQ_DEFAULT_USER}"
set_kv "config/development/identity-service/rabbitmq.password" "${RABBITMQ_DEFAULT_PASS}"
set_kv "config/development/identity-service/rabbitmq.vhost" "/"
set_kv "config/development/identity-service/redis.url" "redis://redis:6379"
set_kv "config/development/identity-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/identity-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/identity-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/identity-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/identity-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development/user-service/port" "3000"
set_kv "config/development/user-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-user:5432/user_db"
set_kv "config/development/user-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/user-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/user-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/user-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/user-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/user-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development/exam-service/port" "3000"
set_kv "config/development/exam-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-exam:5432/exam_db"
set_kv "config/development/exam-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/exam-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/exam-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/exam-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/exam-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/exam-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development/exam-service/services.question.baseUrl" "http://question-service:3000"
set_kv "config/development/exam-service/services.user.baseUrl" "http://user-service:3000"
set_kv "config/development/question-service/port" "3000"
set_kv "config/development/question-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-question:5432/question_db"
set_kv "config/development/question-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/question-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/question-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/question-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/question-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/question-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development/course-service/port" "3000"
set_kv "config/development/course-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-course:5432/course_db"
set_kv "config/development/course-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/course-service/redis.url" "redis://redis:6379"
set_kv "config/development/course-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/course-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/course-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/course-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/course-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development/notification-service/port" "3000"
set_kv "config/development/notification-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-notification:5432/notification_db"
set_kv "config/development/notification-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/notification-service/notification.warningRetryIntervalMs" "300000"
set_kv "config/development/notification-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/notification-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/notification-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/notification-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/notification-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development/notification-service/smtp.host" "${KEYCLOAK_SMTP_HOST:-mailpit}"
set_kv "config/development/notification-service/smtp.port" "${KEYCLOAK_SMTP_PORT:-1025}"
set_kv "config/development/notification-service/smtp.user" "${KEYCLOAK_SMTP_USER:-}"
set_kv "config/development/notification-service/smtp.pass" "${KEYCLOAK_SMTP_PASSWORD:-}"
set_kv "config/development/notification-service/smtp.from" "${KEYCLOAK_SMTP_FROM:-no-reply@luyen-thi-lai-xe.local}"
set_kv "config/development/notification-service/smtp.secure" "${KEYCLOAK_SMTP_SSL:-false}"
set_kv "config/development/notification-service/smtp.starttls" "${KEYCLOAK_SMTP_STARTTLS:-false}"
set_kv "config/development/notification-service/push.fcmCredentials" "${FCM_CREDENTIALS:-}"
set_kv "config/development/notification-service/retry.maxAttempts" "${NOTIFICATION_RETRY_MAX_ATTEMPTS:-3}"
set_kv "config/development/notification-service/retry.intervalMs" "${NOTIFICATION_RETRY_INTERVAL_MS:-300000}"
set_kv "config/development/analytics-service/port" "3000"
set_kv "config/development/analytics-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-analytics:5432/analytics_db"
set_kv "config/development/analytics-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/analytics-service/redis.url" "redis://redis:6379"
set_kv "config/development/analytics-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/analytics-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/analytics-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/analytics-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/analytics-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development/simulation-service/port" "3000"
set_kv "config/development/simulation-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-simulation:5432/simulation_db"
set_kv "config/development/simulation-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/simulation-service/redis.url" "redis://redis:6379"
set_kv "config/development/simulation-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/simulation-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/simulation-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/simulation-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/simulation-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development/media-service/port" "3000"
set_kv "config/development/media-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-media:5432/media_db"
set_kv "config/development/media-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/media-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/media-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/media-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/media-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/media-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
seed_media_storage "development"
set_kv "config/development/audit-service/port" "3000"
set_kv "config/development/audit-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-audit:5432/audit_db"
set_kv "config/development/audit-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672"
set_kv "config/development/audit-service/keycloak.authServerUrl" "http://keycloak:8080"
set_kv "config/development/audit-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development/audit-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development/audit-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development/audit-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"

echo "[Consul] Loading development-local configuration..."
set_kv "config/development-local/shared/log.level" "debug"
set_kv "config/development-local/shared/log.format" "text"
set_kv "config/development-local/shared/node_env" "development-local"
set_kv "config/development-local/shared/public.gateway.url" "${GATEWAY_PUBLIC_URL}"
set_kv "config/development-local/shared/public.keycloak.url" "${KEYCLOAK_PUBLIC_URL}"
set_kv "config/development-local/shared/public.frontend.origin" "${FRONTEND_ORIGIN}"
set_kv "config/development-local/shared/cors.origins" "${KONG_CORS_ORIGINS}"
set_kv "config/development-local/identity-service/port" "3001"
set_kv "config/development-local/identity-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/identity_db"
set_kv "config/development-local/identity-service/database.pool_size" "10"
set_kv "config/development-local/identity-service/database.connection_timeout" "5000"
set_kv "config/development-local/identity-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/identity-service/rabbitmq.username" "${RABBITMQ_DEFAULT_USER}"
set_kv "config/development-local/identity-service/rabbitmq.password" "${RABBITMQ_DEFAULT_PASS}"
set_kv "config/development-local/identity-service/rabbitmq.vhost" "/"
set_kv "config/development-local/identity-service/redis.url" "redis://localhost:6379"
set_kv "config/development-local/identity-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/identity-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/identity-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/identity-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/identity-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/user-service/port" "3002"
set_kv "config/development-local/user-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5433/user_db"
set_kv "config/development-local/user-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/user-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/user-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/user-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/user-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/user-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/exam-service/port" "3003"
set_kv "config/development-local/exam-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5434/exam_db"
set_kv "config/development-local/exam-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/exam-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/exam-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/exam-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/exam-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/exam-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/exam-service/services.question.baseUrl" "http://localhost:3005"
set_kv "config/development-local/exam-service/services.user.baseUrl" "http://localhost:3002"
set_kv "config/development-local/question-service/port" "3005"
set_kv "config/development-local/question-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5436/question_db"
set_kv "config/development-local/question-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/question-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/question-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/question-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/question-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/question-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/course-service/port" "3004"
set_kv "config/development-local/course-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5435/course_db"
set_kv "config/development-local/course-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/course-service/redis.url" "redis://localhost:6379"
set_kv "config/development-local/course-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/course-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/course-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/course-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/course-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/notification-service/port" "3006"
set_kv "config/development-local/notification-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5437/notification_db"
set_kv "config/development-local/notification-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/notification-service/notification.warningRetryIntervalMs" "300000"
set_kv "config/development-local/notification-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/notification-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/notification-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/notification-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/notification-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/notification-service/smtp.host" "${KEYCLOAK_SMTP_HOST:-localhost}"
set_kv "config/development-local/notification-service/smtp.port" "${KEYCLOAK_SMTP_PORT:-1025}"
set_kv "config/development-local/notification-service/smtp.user" "${KEYCLOAK_SMTP_USER:-}"
set_kv "config/development-local/notification-service/smtp.pass" "${KEYCLOAK_SMTP_PASSWORD:-}"
set_kv "config/development-local/notification-service/smtp.from" "${KEYCLOAK_SMTP_FROM:-no-reply@luyen-thi-lai-xe.local}"
set_kv "config/development-local/notification-service/smtp.secure" "${KEYCLOAK_SMTP_SSL:-false}"
set_kv "config/development-local/notification-service/smtp.starttls" "${KEYCLOAK_SMTP_STARTTLS:-false}"
set_kv "config/development-local/notification-service/push.fcmCredentials" "${FCM_CREDENTIALS:-}"
set_kv "config/development-local/notification-service/retry.maxAttempts" "${NOTIFICATION_RETRY_MAX_ATTEMPTS_LOCAL:-3}"
set_kv "config/development-local/notification-service/retry.intervalMs" "${NOTIFICATION_RETRY_INTERVAL_MS_LOCAL:-300000}"
set_kv "config/development-local/analytics-service/port" "3007"
set_kv "config/development-local/analytics-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5438/analytics_db"
set_kv "config/development-local/analytics-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/analytics-service/redis.url" "redis://localhost:6379"
set_kv "config/development-local/analytics-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/analytics-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/analytics-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/analytics-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/analytics-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/simulation-service/port" "3008"
set_kv "config/development-local/simulation-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5439/simulation_db"
set_kv "config/development-local/simulation-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/simulation-service/redis.url" "redis://localhost:6379"
set_kv "config/development-local/simulation-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/simulation-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/simulation-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/simulation-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/simulation-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/media-service/port" "3010"
set_kv "config/development-local/media-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5440/media_db"
set_kv "config/development-local/media-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/media-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/media-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/media-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/media-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/media-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
seed_media_storage "development-local"
set_kv "config/development-local/audit-service/port" "3011"
set_kv "config/development-local/audit-service/database.url" "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5441/audit_db"
set_kv "config/development-local/audit-service/rabbitmq.url" "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@localhost:5672"
set_kv "config/development-local/audit-service/keycloak.authServerUrl" "http://localhost:8080"
set_kv "config/development-local/audit-service/keycloak.realm" "luyen-thi-lai-xe-realm"
set_kv "config/development-local/audit-service/keycloak.clientId" "nestjs-backend"
set_kv "config/development-local/audit-service/keycloak.clientSecret" "${KEYCLOAK_CLIENT_SECRET}"
set_kv "config/development-local/audit-service/keycloak.timeoutMs" "${KEYCLOAK_TIMEOUT_MS}"
set_kv "config/development-local/docs-service/port" "3009"
set_kv "config/development-local/docs-service/swagger.services" "identity-service:3001,user-service:3002,exam-service:3003,course-service:3004,question-service:3005,notification-service:3006,analytics-service:3007,simulation-service:3008,media-service:3010,audit-service:3011"

echo "[Consul] Configuration seeding completed"
echo "[Consul] Access Consul UI: http://localhost:8500"
