apiVersion: 1

datasources:
  - name: InfluxDB_K6
    uid: influxdb-k6
    type: influxdb
    access: proxy
    url: http://host.docker.internal:8086
    database: k6
    isDefault: false
    editable: true
